### ISSUE TITLE
plot.bammdata for negative net div rates

### ISSUE THREAD

**Issue by drabosky** [macroevolution/bammtools#26]
plot.bammdata, if log=TRUE, gives error when spex = "se", if net diversification rate is negative. SHould print more informative warning for this situation, or handle it in some other fashion (though not sure how, short of adding a constant to all values)

also: legend labels for log = TRUE should give the rates rather than log(rates)

**Comment by blueraleigh** [comment]
this is dealt with by implementing a safeLog function when spex = "se" to take the logarithm of diversification rates and then using its inverse for generating the color breaks that define the color map.

safeLog(x, inverse = FALSE) {
    if (inverse)
          y =  exp(x) - attr(x, "increment")
    else {
           y = log(x + min(abs(x)) + 0.0001)
           attr(y, "increment") = min(abs(x)) + 0.0001
     }
     return (y)
}
