### ISSUE TITLE
plot.bammdata color scheme

### ISSUE THREAD

**Issue by drabosky** [macroevolution/bammtools#28]
Add support for color_interval for plot.bammdata. At present, the linear color gradient automatically sets the fastest rate to the max color. This means that even with lots of rate heterogeneity, a single super-fast but small clade can cause the rest of the plot to show almost no variation. A better approach might be to have an argument:

interval_color = c(x, y)

where x is a rate at which the minimum and maximum colors will be observed. So, if you specify

interval_color = c(0.2, 0.5) 

any rates below or equal to 0.2 will get the "slowest" color, and any rates over 0.5 will get the "fastest" color, but between those values, you will have a nice linear gradient. This will make it easy for users to visualize patterns on linear scale while minimizing effects of outliers.

**Comment by ptitle** [comment]
This has now been implemented.
