### ISSUE TITLE
plot.credibleshiftset bug

### ISSUE THREAD

**Issue by drabosky** [macroevolution/bammtools#31]
Bug in plot.credibleshiftset

Chokes when some options to plot.bammdata are passed indirectly

Eg passing lwd gives:

Error in assignColorBreaks(cset.bamm$dtrates$rates, spex = spex, ...) : 
  unused argument (lwd = 1.5)

**Comment by drabosky** [comment]
I created this, indirectly, by adding the additional arguments …. to the call to assignColorBreaks, because it was failing to correctly plot rates on trees when log = T. But now it passes other args to plot.bammdata to assignColorBreaks

**Comment by blueraleigh** [comment]
this looks OK now
