### ISSUE TITLE
plot.bammdata color.interval

### ISSUE THREAD

**Issue by drabosky** [macroevolution/bammtools#44]
Default behavior in plot.bammdata is currently to not plot colors outside of range given by color.interval. Suppose color.interval = c(0.25, 1). I think a rate of 1.5 should receive the max color, and a value of 0.1 should receive the min. So all rates still get a color...but the scale only gives a metric interpretation to values between min and max.

**Comment by ptitle** [comment]
Is this not already how it works? Seems to work with the following example:

```
data(whales, events.whales)
ed <- getEventData(whales, events.whales, burnin=0.25, nsamples=500)

# default plot
plot(ed, legend=T, lwd=2)

# constraining the color ramp to between
plot(ed, legend=T, lwd=2, color.interval=c(0.14, 0.2))

```
In the second plot, the color ramp is generated between the user-supplied min and max, and rates outside of that interval are given those min and max values.

**Comment by ptitle** [comment]
Ok, this should be fixed now. If the color.interval range is small relative to the range of rates in the bammdata object, the color ramp becomes very coarse. I'm working on improving that.

**Comment by ptitle** [comment]
Changes have been made such that the color ramp is high resolution when color.interval is defined.
