### ISSUE TITLE
Thinning option

### ISSUE THREAD

**Issue by josephwb** [macroevolution/bammtools#46]
BAMMtools should have a thinning option for people that over-sampled. `nsamples` is nice for excessively large files, but not for files that were sampled too frequently.

What is typically done is integer arg is given for the frequency of resampling e.g. '5' would mean "retain every 5th sample". This should be in terms of the existing samples, _not_ the generations of the origin al run; in the latter case, the user has to figure out what the sampling frequency originally, was, and then the desired sampling frequency mapped onto that. In the former case, '5' would mean "retain every 5th sample" whether the original sampling frequency was every 10 generations or every 50000.

**Comment by drabosky** [comment]
Hi Joseph

I’m not entirely sure what you mean by nsamples not being adequate. nsamples looks at a posterior sample and thins to an arbitrary density. If you took 50,000 samples and want to thin to 1000 equally spaced samples, nsamples = 1000 will accomplish this. Which would be the same as thinning with a frequency of 50.

For adequately sampled (or oversampled) mcmc analyses, I’d argue that it’s better to think about the total number of samples we want, not how frequently things are sampled. But maybe I don’t understand what you mean?

~Dan

**Comment by josephwb** [comment]
Oh, so that _does_ thinning. I thought it just took the first N number of samples after burnin. Never mind!
