### ISSUE TITLE
Trouble in getEventData

### ISSUE THREAD

**Issue by BeardLi** [macroevolution/bammtools#47]
Hi,
  I ran into a trouble when I use getEventData to input my BAMM outputs:
  Here is my codes:
![图片](https://user-images.githubusercontent.com/65237065/90598624-fb89c980-e225-11ea-9b1f-0d10c4318736.png)
  And then, the output is:
  
![图片](https://user-images.githubusercontent.com/65237065/90598813-591e1600-e226-11ea-8f74-c2f8aeb98299.png)

 I don't know what is the "getmrca".

Thank you for your patience.

**Comment by ptitle** [comment]
Hi,
Did you run a trait or a diversification analysis with BAMM? If this was a trait analysis, then you need to specify that in getEventData(), with `type = 'trait'`. The fact that you are only getting 5 samples from 90% of the posterior also makes me wonder if the BAMM run was not set up properly. You should be getting hundreds or thousands of posterior samples.

**Comment by BeardLi** [comment]
Hi,
It's a diversification analysis. I was running a test, so there were only. 5 samples. I have add it to 500 samples, but same error happen again.
I wonder how this "Error in getmrca" hanppens?

**Comment by ptitle** [comment]
I think I would need to see the files myself to figure out what is going on. Can you send me the tree and event data file to pascal.title@stonybrook.edu? Then I'll see if I get the same error as you.

**Comment by blueraleigh** [comment]
Please ensure the following returns `FALSE`:
```r
setwd("/data3/bamm")
tree <- read.tree("p55.tre")
x <- read.csv("event_data", header=TRUE, stringsAsFactors=FALSE)
anyNA(match(x$leftchild, tree$tip.label))
```
If not, this indicates a mismatch in tip labels present in the tree file and eventdata file passed to getEventData, in which case a different tree may have been used to generate the eventdata file.
